GO
/****** FHQQ313596790 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE BPMMODEL (
 		BPMMODEL_ID  nvarchar(100) NOT NULL,
		ID_ nvarchar(64) DEFAULT NULL,
		REV_ int NOT NULL,
		NAME_ nvarchar(255) DEFAULT NULL,
		KEY_ nvarchar(255) DEFAULT NULL,
		CATEGORY_ nvarchar(255) DEFAULT NULL,
		CREATE_TIME_ nvarchar(23) DEFAULT NULL,
		LAST_UPDATE_TIME_ nvarchar(23) DEFAULT NULL,
		VERSION_ int NOT NULL,
		META_INFO_ nvarchar(4000) DEFAULT NULL,
		DEPLOYMENT_ID_ nvarchar(64) DEFAULT NULL,
		EDITOR_SOURCE_VALUE_ID_ nvarchar(64) DEFAULT NULL,
		EDITOR_SOURCE_EXTRA_VALUE_ID_ nvarchar(64) DEFAULT NULL,
		TENANT_ID_ nvarchar(255) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[BPMMODEL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
