-- ----------------------------
-- Table structure for "C##FHADMIN"."BPMMODEL"
-- ----------------------------
-- DROP TABLE "C##FHADMIN"."BPMMODEL";
CREATE TABLE "C##FHADMIN"."BPMMODEL" (
	"ID_" VARCHAR2(64 BYTE) NULL ,
	"REV_" NUMBER(11) NULL ,
	"NAME_" VARCHAR2(255 BYTE) NULL ,
	"KEY_" VARCHAR2(255 BYTE) NULL ,
	"CATEGORY_" VARCHAR2(255 BYTE) NULL ,
	"CREATE_TIME_" VARCHAR2(23 BYTE) NULL ,
	"LAST_UPDATE_TIME_" VARCHAR2(23 BYTE) NULL ,
	"VERSION_" NUMBER(11) NULL ,
	"META_INFO_" VARCHAR2(4000 BYTE) NULL ,
	"DEPLOYMENT_ID_" VARCHAR2(64 BYTE) NULL ,
	"EDITOR_SOURCE_VALUE_ID_" VARCHAR2(64 BYTE) NULL ,
	"EDITOR_SOURCE_EXTRA_VALUE_ID_" VARCHAR2(64 BYTE) NULL ,
	"TENANT_ID_" VARCHAR2(255 BYTE) NULL ,
	"BPMMODEL_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."ID_" IS '备注1';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."REV_" IS '备注2';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."NAME_" IS '备注3';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."KEY_" IS '备注4';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."CATEGORY_" IS '备注5';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."CREATE_TIME_" IS '备注6';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."LAST_UPDATE_TIME_" IS '备注7';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."VERSION_" IS '备注8';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."META_INFO_" IS '备注9';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."DEPLOYMENT_ID_" IS '备注10';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."EDITOR_SOURCE_VALUE_ID_" IS '备注11';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."EDITOR_SOURCE_EXTRA_VALUE_ID_" IS '备注12';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."TENANT_ID_" IS '备注13';
COMMENT ON COLUMN "C##FHADMIN"."BPMMODEL"."BPMMODEL_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table BPMMODEL
-- ----------------------------

-- ----------------------------
-- Checks structure for table "C##FHADMIN"."BPMMODEL"

-- ----------------------------

ALTER TABLE "C##FHADMIN"."BPMMODEL" ADD CHECK ("BPMMODEL_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "C##FHADMIN"."BPMMODEL"
-- ----------------------------
ALTER TABLE "C##FHADMIN"."BPMMODEL" ADD PRIMARY KEY ("BPMMODEL_ID");
