
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `BPMMODEL`
-- ----------------------------
DROP TABLE IF EXISTS `BPMMODEL`;
CREATE TABLE `BPMMODEL` (
 		`BPMMODEL_ID` varchar(100) NOT NULL,
		`ID_` varchar(64) DEFAULT NULL COMMENT '备注1',
		`REV_` int(11) NOT NULL COMMENT '备注2',
		`NAME_` varchar(255) DEFAULT NULL COMMENT '备注3',
		`KEY_` varchar(255) DEFAULT NULL COMMENT '备注4',
		`CATEGORY_` varchar(255) DEFAULT NULL COMMENT '备注5',
		`CREATE_TIME_` varchar(23) DEFAULT NULL COMMENT '备注6',
		`LAST_UPDATE_TIME_` varchar(23) DEFAULT NULL COMMENT '备注7',
		`VERSION_` int(11) NOT NULL COMMENT '备注8',
		`META_INFO_` varchar(4000) DEFAULT NULL COMMENT '备注9',
		`DEPLOYMENT_ID_` varchar(64) DEFAULT NULL COMMENT '备注10',
		`EDITOR_SOURCE_VALUE_ID_` varchar(64) DEFAULT NULL COMMENT '备注11',
		`EDITOR_SOURCE_EXTRA_VALUE_ID_` varchar(64) DEFAULT NULL COMMENT '备注12',
		`TENANT_ID_` varchar(255) DEFAULT NULL COMMENT '备注13',
  		PRIMARY KEY (`BPMMODEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
